title: mgreau.com 
author: Maxime Gréau
local_tz: Europe/Paris
interpolate: true
base_url: http://localhost:4242

asciidoctor:
  :compact: true
  :eruby: erubis
  :attributes:
    idprefix: ''
    idseparator: '-'

profiles:
  production:
    base_url: http://mgreau.github.io/blog-awestruct-asciidoctor
    deploy:
      host: github_pages
      # use gh-branch for repositories other than <username>.github.io
      branch: gh-pages
      # use master branch for <username>.github.io repository
      #branch: master
