title: mgreau.com 
author: Maxime Gréau
local_tz: Europe/Paris
interpolate: true
base_url: http://localhost:4242
disqus: mgreau
disqus_developer: true

asciidoctor:
  :compact: true
  :eruby: erubis
  :attributes:
    idprefix: ''
    idseparator: '-'
    source-highlighter: coderay
    coderay-css: style
    icons: font

profiles:
  development:
    base_url: http://localhost:4242
    disqus: mgreau
    disqus_developer: true
  production:
    base_url: http://mgreau.github.io/
    google_analytics: UA-20147445-1
    disqus: mgreau
    disqus_generate_id: true
    disqus_developer: false
    deploy:
      host: github_pages
      # use gh-branch for repositories other than <username>.github.io
      branch: master
      # use master branch for <username>.github.io repository
      #branch: master
